export const ErrorCode = {
  EMAIL_REQUIRED: "EMAIL_REQUIRED",
  INVALID_EXPIRED_TOKEN: "INVALID_EXPIRED_TOKEN",
  TOO_MANY_REQUESTS: "TOO_MANY_REQUESTS",
  INVALID_EMAIL_PWD: "INVALID_EMAIL_PWD",
  USER_DEACTIVATED: "USER_DEACTIVATED",
  EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",
  DUPLICATE_ENTRY: "DUPLICATE_ENTRY",
} as const;
